#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../.." && pwd)"
# shellcheck disable=SC1091
source "${script_dir}/common.sh"

export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-$(git -C "${repo_root}" show -s --format=%ct HEAD)}"

require_command repo
require_command git
require_command sha256sum

lock_file="${SOURCE_LOCK:-${repo_root}/aesl/manifests/lineage-20-lock.xml}"
[[ -s "${lock_file}" ]] || die "reviewed source lock missing: ${lock_file}"

android_dir="${ANDROID_WORKSPACE:-${repo_root}/.android-workspace}"
output_dir="${OUTPUT_DIR:-${repo_root}/out-aesl}"
mkdir -p "${android_dir}" "${output_dir}"
cd "${android_dir}"

# The reviewed lock is already a complete flattened manifest. Loading it as a
# standalone manifest avoids reapplying include/remove directives from the
# mutable upstream manifest checkout.
if [[ -d .repo ]]; then
    # repo cannot convert a damaged or non-standalone manifest checkout in
    # place. Reset only manifest metadata; retain project-objects and checked
    # out sources in the persistent workspace.
    rm -rf .repo/manifests .repo/manifests.git
    rm -f .repo/manifest.xml
fi
repo init -u "file://${lock_file}" --standalone-manifest --git-lfs
GIT_CONFIG_COUNT=1 \
    GIT_CONFIG_KEY_0=http.version \
    GIT_CONFIG_VALUE_0=HTTP/1.1 \
    repo sync -c --no-tags --force-checkout -j"${JOBS:-8}"

# Generated by the locked Android source checkout.
# shellcheck disable=SC1091
source build/envsetup.sh
apply-waydroid-patches
export TARGET_USE_MESA=true
lunch "${AESL_LUNCH_TARGET}"
m -j"${JOBS:-8}" systemimage vendorimage

install -m 0644 "${OUT}/system.img" "${output_dir}/system.img"
install -m 0644 "${OUT}/vendor.img" "${output_dir}/vendor.img"
cp "${lock_file}" "${output_dir}/source-manifest.xml"
(
    cd "${output_dir}"
    sha256sum system.img vendor.img source-manifest.xml > SHA256SUMS
)

python3 "${script_dir}/write-build-info.py" \
    --output "${output_dir}/build-info.json" \
    --source-lock "${output_dir}/source-manifest.xml" \
    --target "${AESL_LUNCH_TARGET}"

# Preserve Android's generated licence/provenance inputs where available.
find "${OUT}" -maxdepth 2 -type f \
    \( -name '*license*' -o -name 'installed-files*.txt' \) \
    -exec cp -t "${output_dir}" {} + 2>/dev/null || true
