#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../.." && pwd)"
# shellcheck disable=SC1091
source "${script_dir}/common.sh"

export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-$(git -C "${repo_root}" show -s --format=%ct HEAD)}"

require_command repo
require_command git
require_command sha256sum

lock_file="${SOURCE_LOCK:-${repo_root}/aesl/manifests/lineage-20-lock.xml}"
[[ -s "${lock_file}" ]] || die "reviewed source lock missing: ${lock_file}"

android_dir="${ANDROID_WORKSPACE:-${repo_root}/.android-workspace}"
output_dir="${OUTPUT_DIR:-${repo_root}/out-aesl}"
mkdir -p "${android_dir}" "${output_dir}"
cd "${android_dir}"

repo init -u https://github.com/LineageOS/android.git \
    -b "${AESL_LINEAGE_BRANCH}" --git-lfs
cp "${lock_file}" .repo/manifests/aesl-locked.xml
repo init -m aesl-locked.xml
repo sync -c --no-tags -j"${JOBS:-8}"

# Generated by the locked Android source checkout.
# shellcheck disable=SC1091
source build/envsetup.sh
apply-waydroid-patches
export TARGET_USE_MESA=true
lunch "${AESL_LUNCH_TARGET}"
m -j"${JOBS:-8}" systemimage vendorimage

install -m 0644 "${OUT}/system.img" "${output_dir}/system.img"
install -m 0644 "${OUT}/vendor.img" "${output_dir}/vendor.img"
cp "${lock_file}" "${output_dir}/source-manifest.xml"
(
    cd "${output_dir}"
    sha256sum system.img vendor.img source-manifest.xml > SHA256SUMS
)

python3 "${script_dir}/write-build-info.py" \
    --output "${output_dir}/build-info.json" \
    --source-lock "${output_dir}/source-manifest.xml" \
    --target "${AESL_LUNCH_TARGET}"

# Preserve Android's generated licence/provenance inputs where available.
find "${OUT}" -maxdepth 2 -type f \
    \( -name '*license*' -o -name 'installed-files*.txt' \) \
    -exec cp -t "${output_dir}" {} + 2>/dev/null || true
